########################################################################################################################
#
# ██╗░░██╗██╗████████╗░██████╗
# ██║░██╔╝██║╚══██╔══╝██╔════╝
# █████═╝░██║░░░██║░░░╚█████╗░
# ██╔═██╗░██║░░░██║░░░░╚═══██╗
# ██║░╚██╗██║░░░██║░░░██████╔╝
# ╚═╝░░╚═╝╚═╝░░░╚═╝░░░╚═════╝░
#
# Documentation: https://zessentials.groupez.dev/modules/kits
#
########################################################################################################################

enable: true

# Change the display of the kits
#
# IN_LINE: Displays a message with the list of kits on the same line
# INVENTORY: Displays the kits in an inventory
# MULTI_LINE: Displays a message with a header and footer (optional) and a message per kits
display: IN_LINE

# Gives kits when the player joins the server for the first time
kits-on-first-join:
  - "tools"